language: python
python:
  - 2.7
install: "pip install -r requirements.txt; pip install -r test-requirements.txt"
services:
    - redis-server
before_script:
    - psql -c 'create database halliganhelper;' -U postgres
    - sudo redis-server /etc/redis/redis.conf --port 6666
script: "pytest"
after_success:
    - bash <(curl -s https://codecov.io/bash)
