- name: add the vassals folder to the webapps group
  file: name="/etc/uwsgi/vassals" group=webapps

- name: make directories for halliganhelper
  file: name="/webapps/{{ item }}" state=directory group=webapps owner=hh
  with_items:
    - hh
    - hh/envs
    - hh/src

- name: Make directory for HH logs
  file: name=/var/log/hh state=directory owner=hh group=webapps 

- name: Install halliganhelper nginx conf
  template: src=halliganhelper.nginx.jinja2 dest=/etc/nginx/sites-enabled/halliganhelper.conf
  register: halliganhelper_nginx_conf
  notify: reload nginx

- name: Reload nginx
  service: name=nginx state=reloaded
  when: halliganhelper_nginx_conf | changed

- name: install halliganhelper vassals
  template: dest="/etc/uwsgi/vassals/{{ item }}" src="{{ item }}.jinja2" group=webapps
  with_items:
    - uwsgi-base.ini
    - uwsgi-halliganhelper.ini
    - uwsgi-halliganhelper-sockets.ini


- name: Make location for bare halliganhelper git repository
  file: path=~/deployable-repos/ state=directory
  become: no

- name: Make bare halliganhelper git repo
  command: git init --bare halliganhelper.git chdir=~/deployable-repos
  become: no

- name: Install post-receive
  template: src=post-receive.jinja2 dest=~/deployable-repos/halliganhelper.git/hooks/post-receive mode=u+x
  become: no

- name: Make directories for static and media files
  file: path="/webapps/{{ item }}/halliganhelper" group=webapps owner=hh state=directory
  with_items:
    - staticfiles
    - mediafiles

- name: ensure uwsgi is started
  service: name=uwsgi state=started
  ignore_errors: yes
