- name: add the vassals folder to the webapps group
  file: name="/etc/uwsgi/vassals" group=webapps

- name: make directories for halliganhelper
  file: name="/webapps/{{ item }}" state=directory group=webapps owner=hh
  with_items:
    - hh
    - hh/envs
    - hh/src

- name: Make directory for HH logs
  file: name=/var/log/hh state=directory owner=hh group=webapps 

- name: Install halliganhelper nginx conf
  template:
    src: halliganhelper.nginx.jinja2
    dest: /etc/nginx/sites-available/halliganhelper.conf
  notify: reload nginx

- name: enable halliganhelper site
  file:
    path: /etc/nginx/sites-enabled/halliganhelper.conf
    state: link
    src: /etc/nginx/sites-available/halliganhelper.conf
    force: yes # there used to be a file here, so we need to force
  notify: reload nginx

- name: remove old uwsgi-base.ini file
  file: path=/etc/uwsgi/vassals/uwsgi-base.ini state=absent

- name: install halliganhelper vassals
  template: dest="/etc/uwsgi/vassals/{{ item }}" src="{{ item }}.jinja2" group=webapps
  with_items:
    - uwsgi-base.skel
    - uwsgi-halliganhelper.ini
    - uwsgi-halliganhelper-sockets.ini


- name: Make location for bare halliganhelper git repository
  file: path=~/deployable-repos/ state=directory
  become: no

- name: Make bare halliganhelper git repo
  command: git init --bare halliganhelper.git chdir=~/deployable-repos
  become: no

- name: Install post-receive
  template: src=post-receive.jinja2 dest=~/deployable-repos/halliganhelper.git/hooks/post-receive mode=u+x
  become: no

- name: Make directories for static and media files
  file: path="/webapps/{{ item }}/halliganhelper" group=webapps owner=hh state=directory
  with_items:
    - staticfiles
    - mediafiles

- name: ensure uwsgi is started
  service: name=uwsgi state=started
  ignore_errors: yes

- name: set environment variables for user
  become: yes
  become_user: hh
  lineinfile: dest=~/.profile create=yes owner=hh line="export {{ item.key }}={{ item.value }}"
  with_dict:
    STATIC_ROOT: "{{ static_root }}"
    MEDIA_ROOT: "{{ media_root }}"
    EMAIL_PASSWORD: "{{ email_password }}"
    DB_PASSWORD: "{{ db_password }}"
    REDIS_PASSWORD: "{{ redis_password }}"
    SECRET_KEY: "{{ django_secret_key }}"
