---
include_ssl: true
subdomain: dev

# Passwords from vault
email_password: "{{ vault_email_password }}"
db_password: "{{ vault_db_password }}"
redis_password: "{{ vault_redis_password }}"
django_secret_key: "{{ vault_django_secret_key }}"

static_root: /webapps/staticfiles/halliganhelper
media_root: /webapps/mediafiles/halliganhelper

# REDIS SETTINGS
redis_port: 6666
redis_bind: 0.0.0.0

# POSTGRES SETTINGS
postgresql_databases:
  - name: halliganhelper
    owner: halliganhelper          # optional; specify the owner of the database
    hstore: yes         # flag to install the hstore extension on this database (yes/no)
    uuid_ossp: yes      # flag to install the uuid-ossp extension on this database (yes/no)
    citext: yes         # flag to install the citext extension on this database (yes/no)

# List of users to be created (optional)
postgresql_users:
  - name: halliganhelper
    pass: "{{ db_password }}"
    encrypted: no       # denotes if the password is already encrypted.

# List of user privileges to be applied (optional)
postgresql_user_privileges:
  - name: halliganhelper                   # user name
    db: halliganhelper                  # database
    priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
    role_attr_flags: "CREATEDB" # role attribute flags


# NodeJS SETTINGS
nodejs_version: "5.x"
nodejs_forever: false

# LetsEncrypt Settings
letsencrypt_webroot_path: /usr/share/nginx/html
letsencrypt_email: tyler@halliganhelper.com
letsencrypt_cert_domains: 
    - "{{ subdomain }}.halliganhelper.com"
# letsencrypt_server: https://acme-staging.api.letsencrypt.org/directory
