- name: ensure nginx is installed
  apt: name=nginx state=latest
  tags: nginx

- name: delete default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - reload nginx
  tags: nginx

- name: install conf file for letsencrypt
  template: src=letsencrypt.conf.jinja2 dest=/etc/nginx/sites-enabled/letsencrypt.conf

- name: reload nginx
  service: name=nginx state=reloaded

- name: Create 'uwsgi' user
  user: name=uwsgi groups=webapps
  tags: uwsgi
