- name: ensure nginx is installed
  apt: name=nginx state=latest
  tags: nginx

- name: delete default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - reload nginx
  tags: nginx

- name: remove old letsencrypt site
  file: path=/etc/nginx/sites-enabled/letsencrypt.conf state=absent
  notify: reload nginx

- name: install conf file for ssl redirect, including letsencrypt exception
  template: src=ssl-redirect.conf.jinja2 dest=/etc/nginx/sites-enabled/ssl-redirect.conf

- name: reload nginx
  service: name=nginx state=reloaded

- name: Create 'uwsgi' user
  user: name=uwsgi groups=webapps
  tags: uwsgi
