---
- hosts: localhost
  remote_user: vagrant
  become: yes
  vars_files:
    - vars/default.yml
    - vars/vagrant.yml
  roles:
    - { role: common, tags: ['common'] }
    - role: DavidWittman.redis
    - role: ANXS.postgresql
    - role: geerlingguy.nodejs
    - { role: vagrant, tags: ['halliganhelper'] }
