---
- hosts: localhost
  remote_user: vagrant
  become: yes
  vars_files:
    - vars/default.yml
    - vars/debug.yml
  roles:
    - role: common
    - role: nginx
    - role: postgres
    - { role: redis, tags: ['redis'] }
    - { role: halliganhelper, tags: ['halliganhelper'] }
