---
- hosts: prod
  remote_user: hh
  become: yes
  vars_files:
    - vars/vault.yml
    - vars/default.yml
    - vars/prod.yml
  roles:
    - { role: common, tags: ['common'] }
    - role: DavidWittman.redis
    - role: ANXS.postgresql
    - role: geerlingguy.nodejs
    - role: nginx
    - { role: ansible-letsencrypt, tags: ['letsencrypt'] }
    - { role: halliganhelper, tags: ['halliganhelper'] }
