# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 05:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tas', '0004_make_tufts_objects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='request',
            name='student',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='has_updated_headshot',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='headshot',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 19, 5, 42, 49, 684060, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='postfix',
            field=models.CharField(default='', help_text=b'The CP of COMP 150CP', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='requestor',
            field=models.ForeignKey(default=1, help_text=b'The student who made the request', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tas.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(help_text=b'The courses a student is registered for.', related_name='students', to='tas.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='headshot',
            field=models.ImageField(default=b'headshots/None/ming.jpg', help_text=b'A headshot of the user', upload_to=b'headshots'),
        ),
        migrations.AddField(
            model_name='student',
            name='ta_jobs',
            field=models.ManyToManyField(help_text=b'The courses a student TAs for.', related_name='tas', through='tas.TA', to='tas.Course'),
        ),
        migrations.AddField(
            model_name='ta',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tas.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, help_text=b'When the TA went on duty'),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='ta',
            field=models.ForeignKey(help_text=b'The TA on duty', on_delete=django.db.models.deletion.CASCADE, to='tas.Student'),
        ),
        migrations.AlterField(
            model_name='request',
            name='when_asked',
            field=models.DateTimeField(auto_now_add=True, help_text=b'When the request was made'),
        ),
        migrations.AlterField(
            model_name='request',
            name='who_solved',
            field=models.ForeignKey(blank=True, help_text=b'The TA who resolved the request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_solved', to='tas.Student'),
        ),
        migrations.RemoveField(
            model_name='ta',
            name='course',
        ),
        migrations.AddField(
            model_name='ta',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tas.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tas.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tas.School'),
            preserve_default=False,
        ),
    ]
