# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tas', '0005_new_table_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='postfix',
            field=models.CharField(default=b'', help_text=b'The CP of COMP 150CP', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolemaildomain',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
