# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 08:30
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import tas.models


class Migration(migrations.Migration):

    dependencies = [
        ('tas', '0008_add_request_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='headshot',
            field=imagekit.models.fields.ProcessedImageField(default=b'blank/blank.jpg', help_text=b'A headshot of the user', upload_to=tas.models.determine_headshot_name),
        ),
    ]
