# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tas', '0009_auto_20160204_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blurb',
            field=models.CharField(default='', help_text=b'A field for TA bios', max_length=255),
            preserve_default=False,
        ),
    ]
