# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 07:25
from __future__ import unicode_literals

from django.db import migrations

import random

HAMBURGER_HELPER_TYPES = [
    'Bacon Cheeseburger',
    'Beef Fried Rice',
    'Beef Pasta',
    'Cheddar Cheese Melt',
    'Cheeseburger Macaroni',
    'Cheese Lover\'s Lasagna',
    'Cheesey Baked Potato',
    'Cheese Beef Pasta',
    'Cheesey Enchilada',
    'Cheesy Hashbrowns',
    'Cheese Italian Beef',
    'Cheesy Italian Shells',
    'Cheesy Ranch Burger',
    'Chili Cheese',
    'Chili Macaroni',
    'Cruncy Taco',
    'Double Cheeseburger Macaroni',
    'Double Cheese Quesadilla',
    'Four Cheese Lasagna',
    'Lasagna',
    'Patty Melt',
    'Philly Cheesesteak',
    'Sloppy Joe',
    'Spaghetti',
    'Supreme Cheese Pizza',
    'Three Cheese',
    'Tomato Basil Penne',
    'Deluxe Cheeseburger Macaroni',
    'Whole Grain Cheeseburger Macaroni',
]


def add_funny_blurb(apps, schema_editor):
    Student = apps.get_model('tas', 'Student')
    msg = 'Hi, my name\'s {}. What\'s my favorite flavor of Hamburger Helper? '
    msg += 'Personally, I love {}'

    for s in Student.objects.all():
        hht = random.choice(HAMBURGER_HELPER_TYPES)
        s.blurb = msg.format(s.user.first_name, hht)
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tas', '0010_create_student_blurb'),
    ]

    operations = [
        migrations.RunPython(add_funny_blurb, migrations.RunPython.noop),
    ]
