# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tas', '0012_dedup_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='request_time_to_live',
            field=models.IntegerField(default=3, help_text=b'The time until a request for a course times out'),
        ),
    ]
